### ISSUE TITLE
转移凭证先删除旧的再添加新的

### ISSUE THREAD

**Issue by ZbkSou** [jazzlost/Substrate-OneBlock-Lessons#1]
https://github.com/jazzlost/Substrate-OneBlock-Lessons/blob/18fe8c479928d38449be59d5f2bbda3659a46fc2/Lesson5/substrate-node-template/pallets/poe/src/lib.rs#L117

**Comment by jazzlost** [comment]
这里insert如果是已存在的key，就回覆盖val值，应该也是可以的

**Comment by jazzlost** [comment]
这里insert如果是已存在的key，就回覆盖val值，应该也是可以的吧
